# Data integration (Merging, Joining and Concatenation)

### Created by
Laureen Otieno

In [17]:
import pandas as pd

## CHALLENGE 1: Creating 3 DataFrames

### DataFrame 1: Student Info

#### Creating data dictionary for the DataFrame

In [11]:
student_info = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104], 
    "Name": ["Laura", "Benedine", "Ato", "Newman"],
    "Gender": ["F", "M", "M", "M"]
})

In [12]:
pd.DataFrame(student_info)

   Student_ID      Name Gender
0         101     Laura      F
1         102  Benedine      M
2         103       Ato      M
3         104    Newman      M

### DataFrame 2: Test Scores

#### Creating data dictionary for the DataFrame

In [14]:
test_scores = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104], 
    "Math_Score": [88, 92, 79, 85],
    "English_Score": [90, 87, 75, 89]
})

In [15]:
pd.DataFrame(test_scores)

   Student_ID  Math_Score  English_Score
0         101          88             90
1         102          92             87
2         103          79             75
3         104          85             89

### DataFrame 3: Attendance

#### Creating data dictionary for the DataFrame

In [19]:
attendance_data = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104], 
    "Days_Present": [22, 18, 20, 25],
    "Total_Days": [25, 25, 25, 25]
})

In [20]:
pd.DataFrame(attendance_data)

   Student_ID  Days_Present  Total_Days
0         101            22          25
1         102            18          25
2         103            20          25
3         104            25          25

## CHALLENGE 2: Concatenate Vertically

### DataFrame 4: more_students

In [21]:
more_students = pd.DataFrame({
    "Student_ID": [105, 106], 
    "Name": ["Lauren", "Loice"],
    "Gender": ["F", "F"]
})

In [22]:
pd.DataFrame(more_students)

   Student_ID    Name Gender
0         105  Lauren      F
1         106   Loice      F

### Concatenating 2 DataFrames(students_info and more_students)

In [24]:
pd.concat([student_info, more_students], ignore_index=True)
all_students = pd.concat([student_info, more_students], ignore_index=True)

In [25]:
all_students

   Student_ID      Name Gender
0         101     Laura      F
1         102  Benedine      M
2         103       Ato      M
3         104    Newman      M
4         105    Lauren      F
5         106     Loice      F

### CHALLENGE 3: 2 DataFrames
Merge students_info with test_scores

In [27]:
pd.merge(student_info, test_scores, on="Student_ID", how="outer")
merged_scores = pd.merge(student_info, test_scores, on="Student_ID", how="outer")

In [28]:
merged_scores

   Student_ID      Name Gender  Math_Score  English_Score
0         101     Laura      F          88             90
1         102  Benedine      M          92             87
2         103       Ato      M          79             75
3         104    Newman      M          85             89

In [29]:
pd.merge(student_info, test_scores, on="Student_ID", how="inner")
merged_scores = pd.merge(student_info, test_scores, on="Student_ID", how="inner")

In [30]:
merged_scores

   Student_ID      Name Gender  Math_Score  English_Score
0         101     Laura      F          88             90
1         102  Benedine      M          92             87
2         103       Ato      M          79             75
3         104    Newman      M          85             89

### CHALLENGE 4: Merging new DataFrame with Attendance

In [31]:
final_data = pd.merge(merged_scores, attendance_data, on="Student_ID", how="inner")

In [32]:
final_data

,Student_ID,Name,Gender,Math_Score,English_Score,Days_Present,Total_Days
0,101,Laura,F,88,90,22,25
1,102,Benedine,M,92,87,18,25
2,103,Ato,M,79,75,20,25
3,104,Newman,M,85,89,25,25

### CHALLENGE 5: Cleaning the Data
Filling missing values for clarity

In [34]:
Cleaned_data = final_data.fillna("Missing")

In [35]:
Cleaned_data

,Student_ID,Name,Gender,Math_Score,English_Score,Days_Present,Total_Days
0,101,Laura,F,88,90,22,25
1,102,Benedine,M,92,87,18,25
2,103,Ato,M,79,75,20,25
3,104,Newman,M,85,89,25,25

### TO CHECK How many MISSING values we have in each field

In [37]:
missing_values = final_data.isnull().sum()

In [38]:
missing_values

Student_ID       0
Name             0
Gender           0
Math_Score       0
English_Score    0
Days_Present     0
Total_Days       0
dtype: int64